AG\PrincipalBundle\Entity\Producto:
    type: entity 
    table: productos
    manyToOne:
        category:
            targetEntity: Category
            inversedBy: productos
            joinColumn:
                name: categoryID
                referencedColumnName: id
    oneToMany:
        fotos:
            targetEntity: Foto
            mappedBy: producto
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        categoryID:
            type: integer
        clave:
            type: string
            length: 100
        Nombre:
            type: string
            length: 150
        Slug:
            type: string
            length: 100
        Precio:
            type: float
        PrecioEspecial:
            type: float
            nullable: true
        Medidas:
            type: string
            length: 100
            nullable: true
        Interior:
            type: string
            length: 100
            nullable: true
        Exterior:
            type: string
            length: 100
            nullable: true
        Colores:
            type: string
            length: 100
            nullable: true
        Paginas:
            type: integer
            nullable: true
        Encuadernacion:
            type: string
            length: 100
            nullable: true
        Publicidad:
            type: string
            length: 150
            nullable: true
        Empaque:
            type: string
            length: 100
            nullable: true
        Caracteristicas:
            type: text
            nullable: true
        Descripcion:
            type: text
            nullable: true