AG\PrincipalBundle\Entity\SliderImg:
    type: entity 
    table: imagenes_slider
    id:
        id:
            type: integer
            generator: 
                strategy: AUTO
    fields:
        link:
            type: string
            length: 100
            nullable: true
        path:
            type: string
            length: 255