# app/config/security.yml
security:

    role_hierarchy:
        ROLE_ADMIN: [ROLE_DISTRIBUIDOR, ROLE_ESPECIAL]
        ROLE_ESPECIAL: ROLE_DISTRIBUIDOR

    firewalls:
        main:
            pattern:    ^/
            anonymous: ~
            http_basic:
                realm: "Sitio para administradores y distribuidores"
            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/admin/, roles: ROLE_ADMIN }
        - { path: ^/admin$, roles: ROLE_ADMIN }
        - { path: ^/panel-control$, roles: ROLE_DISTRIBUIDOR }
        - { path: ^/precios-especiales$, roles: ROLE_ESPECIAL }
        - { path: ^/distribuidor/, roles: ROLE_DISTRIBUIDOR }
        - { path: ^/distribuidor$, roles: ROLE_DISTRIBUIDOR }

    providers:
        in_memory:
            memory:
                users:
                    Enrique:  { password: 987410, roles: 'ROLE_ADMIN' }
                    Sergio: { password: 3315, roles: 'ROLE_ADMIN' }
                    Gustavo: { password: 12345, roles: 'ROLE_ESPECIAL' }
                    Distribuidor: { password: distribuidor, roles: 'ROLE_DISTRIBUIDOR' }

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext