# app/config/security.yml
security:
    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            http_basic:
                realm: "Secured Demo Area"

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/admin$, roles: ROLE_ADMIN }

    providers:
        in_memory:
            memory:
                users:
                    Valerio:  { password: 987410, roles: 'ROLE_ADMIN' }
                    otro: { password: kitten, roles: 'ROLE_USER' }

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext