ag_principal_homepage:
    pattern:  /
    defaults: { _controller: AGPrincipalBundle:Default:index }
ag_principal_catalgo_admin:
    pattern:  /admin/catalogo
    defaults: { _controller: AGPrincipalBundle:Default:catalogoAdmin }
ag_principal_nuevo_producto:
    pattern:  /admin/nuevoproducto
    defaults: { _controller: AGPrincipalBundle:Default:nuevoProducto }
ag_principal_nuevo_pedido:
    pattern:  /vendedor/nuevopedido
    defaults: { _controller: AGPrincipalBundle:Default:nuevoPedido }