user_logout:
       pattern:  /logout
ag_principal_homepage:
    pattern:  /
    defaults: { _controller: AGPrincipalBundle:Default:index }
ag_principal_panel_control:
    pattern:  /panel-control
    defaults: { _controller: AGPrincipalBundle:Default:panelControl }
ag_principal_slider_admin:
    pattern:  /admin/slider
    defaults: { _controller: AGPrincipalBundle:Default:sliderAdmin }
ag_principal_borrar_sliderimg:
    pattern:  /admin/borrar-sliderimg/{imagenId}
    defaults: { _controller: AGPrincipalBundle:Default:borrarSliderImg }
ag_principal_catalgo_admin:
    pattern:  /admin/catalogo
    defaults: { _controller: AGPrincipalBundle:Default:catalogoAdmin }
ag_principal_nuevo_producto:
    pattern:  /admin/nuevoproducto
    defaults: { _controller: AGPrincipalBundle:Default:nuevoProducto }
ag_principal_borrar_producto:
    pattern:  /admin/borrar-producto/{productoId}
    defaults: { _controller: AGPrincipalBundle:Default:borrarProducto }
ag_principal_editar_producto:
    pattern:  /admin/editar-producto/{productoId}
    defaults: { _controller: AGPrincipalBundle:Default:editarProducto }
ag_principal_borrar_foto:
    pattern:  /admin/borrar-foto/{fotoId}
    defaults: { _controller: AGPrincipalBundle:Default:borrarFoto }
ag_principal_precios_especiales:
    pattern:  /precios-especiales
    defaults: { _controller: AGPrincipalBundle:Default:preciosEspeciales }
ag_principal_nuevo_pedido:
    pattern:  /vendedor/nuevopedido
    defaults: { _controller: AGPrincipalBundle:Default:nuevoPedido }
ag_principal_conocenos:
    pattern:  /informacion-sobre-agarti
    defaults: { _controller: AGPrincipalBundle:Default:conocenos }
ag_principal_servicios:
    pattern:  /servicios-de-personalizacion
    defaults: { _controller: AGPrincipalBundle:Default:servicios }
ag_principal_contacto:
    pattern:  /contacto
    defaults: { _controller: AGPrincipalBundle:Default:contacto }
ag_principal_categorias:
    pattern:  /{categoriaSlug}
    defaults: { _controller: AGPrincipalBundle:Default:vistaCategoria }
ag_principal_productos:
    pattern:  /{categoriaSlug}/{productoSlug}
    defaults: { _controller: AGPrincipalBundle:Default:vistaProducto }