#parameters:
#    nw_principal.controller.forms.class: NW\PrincipalBundle\Controller\FormsController
#services:
#    nw_principal.forms.controller:
#        class: "%nw_principal.controller.forms.class%"
#services:
#    nw_principal.forms.controller.manyForms:
#        class: NW\PrincipalBundle\Controller\FormsController\manyFormsAction
parameters:
    producto_service.class: AG\PrincipalBundle\Servicios\Producto

services:
    producto_service:
        class:     %producto_service.class%
        arguments: [@router, @doctrine.orm.entity_manager]